version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: jtro-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - jtro-network

  frontend:
    build:
      context: ./frontend
    container_name: jtro-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - jtro-network

networks:
  jtro-network:
    driver: bridge